--- 
- name: Kubernetes Application Deployment
  hosts: local
  become: true
  tasks:
    - name: create new  deployment
      command: kubectl apply -f Deployment.yml --validate=false
    - name: create new service
      command: kubectl apply -f Service.yml --validate=false
